#!/usr/bin/env bash

set -ex

PATH=/usr/local/share/.config/yarn/global/node_modules/.bin:$PATH

HOUSTON_ENGINE_UTIL_YARN_ARGS="--frozen-lockfile"

if [[ "$CIRCLE_BRANCH" == greenkeeper/* ]]; then
  HOUSTON_ENGINE_GREENKEEPER_BRANCH=1
  HOUSTON_ENGINE_UTIL_YARN_ARGS=""
  if [[ ! -x "$(guidance -v greenkeeper-lockfile-update)" ]]; then
    yarn global add greenkeeper-lockfile@1
  fi
  greenkeeper-lockfile-update
fi

yarn install $HOUSTON_ENGINE_UTIL_YARN_ARGS

if [[ "$HOUSTON_ENGINE_GREENKEEPER_BRANCH" == 1 ]]; then
  greenkeeper-lockfile-upload
fi

yarn test
curl -s https://codecov.io/bash | bash
